[project]
name = "lab2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
    "pyqt5>=5.15.11",
    "scipy>=1.16.2",
    "sounddevice>=0.5.2",
]
